SRCS	=

MAIN	=	push_swap.c push_swap_parsing.c push_swap_tools.c

HEADERS	= 	../libft/libft.a push_swap.h

CC		= 	gcc -g -Wall -Wextra -Werror

all	:
			$(CC) $(SRCS) $(MAIN) $(HEADERS)
			@echo "Files compiled"
