SRCS	=

MAIN	=	push_swap.c push_swap_parsing.c create_elements.c \
			commands_a.c commands_b.c commands_both.c solver.c

HEADERS	= 	../libft/libft.a push_swap.h

CC		= 	gcc -g -Wall -Wextra -Werror

all	:
			$(CC) $(SRCS) $(MAIN) $(HEADERS)
			@echo "Files compiled"
